name: flyreel_sdk_flutter
description: "Flutter plugin for Flyreel SDK - an advanced property survey solution for U.S. insurance carriers."
version: 0.0.4
homepage: https://flyreel.co

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.lexisnexis.risk.flyreel_sdk_flutter
        pluginClass: FlyreelSdkFlutterPlugin
      ios:
        pluginClass: FlyreelSdkFlutterPlugin
